baseURL = ""
languageCode = "en-us"
title = "Palace.Lucas"
theme = "palace-v1.0"
markdown = "blackfriday"
googleAnalytics = ""

[params]
    author = "Lucas"
    description = "Palace for Lucas Zapico"
    githubUsername = "LucasZapico"
    favicon = "img/favicon-32x32.ico"
    images = ["site-feature-image.jpg"]




[menu]

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "home"
  url = "/"
  weight = 1
